input: 
    let foo = fn (x) {
      if x < 0 {
        throw "x must be positive";
      }
      return x;
    };
    let bar = fn (x) {
      let result = try {
        foo(x);
      } catch {
        | _ => 0
      };
      return result;
    };
    
output: Error Error in Ln: 8 Col: 9
Expecting: ';' or '}'
